### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by iamSiiN**
based from A320_MCDU-laser.svg, this is a fusion360 3d model of MCDU smd pcb housing with base features hinge and handle.

### CODE REVIEW

**Comment by tigert** [comment]
Hello, as I don't have Fusion, would it also be possible to export a STEP file that can be useful and editable with other CAD tools?

**Comment by datamann** [comment]
> Hello, as I don't have Fusion, would it also be possible to add a STEP file that can be useful and editable with other CAD tools?

Fusion 360 is free for hobbyists however I do believe you need the paid version to export as STEP file.

**Comment by iamSiiN** [comment]
[MCDU with handle.zip](https://github.com/MobiFlight/mobiflight-panels/files/13777228/MCDU.with.handle.zip)

added a step file.

**Comment by FSXLiveriesdotcom** [comment]
@datamann nope, you don't need paid version for that.

**Comment by tigert** [comment]
yea, it would make sense to have the STEP in the git repo too, can you add it to the pull request also?

**Comment by FSXLiveriesdotcom** [comment]
Not at this moment. First I will have to clean up everything. as it is a big mess with unnecessary sketches, in some cases >10 of them per file :)

**Comment by tigert** [comment]
I can add it from the zip, no problem

**Comment by tigert** [comment]
Ok, put the step there too.

**Pull request merged**
